# Generated by Django 3.2.16 on 2022-10-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='imgg',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nam',
        ),
    ]
