# Generated by Django 3.2.16 on 2022-10-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20221025_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='imgg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='nam',
            new_name='name',
        ),
    ]
