# Generated by Django 3.2.16 on 2022-10-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20221025_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
